/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrape404
 */
interface BatchScrape404 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrape404Error extends ApiError<BatchScrape404> {}
