/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrapeErrors429
 */
interface BatchScrapeErrors429 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrapeErrors429Error extends ApiError<BatchScrapeErrors429> {}
