/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrapeErrors402
 */
interface BatchScrapeErrors402 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrapeErrors402Error extends ApiError<BatchScrapeErrors402> {}
