/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrape500
 */
interface BatchScrape500 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrape500Error extends ApiError<BatchScrape500> {}
