/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrapeErrors500
 */
interface BatchScrapeErrors500 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrapeErrors500Error extends ApiError<BatchScrapeErrors500> {}
