/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrape402
 */
interface BatchScrape402 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrape402Error extends ApiError<BatchScrape402> {}
