/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BatchScrape429
 */
interface BatchScrape429 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BatchScrape429Error extends ApiError<BatchScrape429> {}
