/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Crawl429
 */
interface Crawl429 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Crawl429Error extends ApiError<Crawl429> {}
