/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of CrawlErrors402
 */
interface CrawlErrors402 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class CrawlErrors402Error extends ApiError<CrawlErrors402> {}
