/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Crawl402
 */
interface Crawl402 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Crawl402Error extends ApiError<Crawl402> {}
