/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of CrawlErrors500
 */
interface CrawlErrors500 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class CrawlErrors500Error extends ApiError<CrawlErrors500> {}
