/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of CrawlErrors429
 */
interface CrawlErrors429 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class CrawlErrors429Error extends ApiError<CrawlErrors429> {}
