/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Crawl500
 */
interface Crawl500 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Crawl500Error extends ApiError<Crawl500> {}
