/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Crawl404
 */
interface Crawl404 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Crawl404Error extends ApiError<Crawl404> {}
