/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of CrawlActive402
 */
interface CrawlActive402 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class CrawlActive402Error extends ApiError<CrawlActive402> {}
