/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of DeepResearch404
 */
interface DeepResearch404 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class DeepResearch404Error extends ApiError<DeepResearch404> {}
