/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of DeepResearch400
 */
interface DeepResearch400 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class DeepResearch400Error extends ApiError<DeepResearch400> {}
