/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Extract400
 */
interface Extract400 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Extract400Error extends ApiError<Extract400> {}
