/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Extract500
 */
interface Extract500 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Extract500Error extends ApiError<Extract500> {}
