/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of FeedbackErrorResponse
 */
interface FeedbackErrorResponse {
  success: boolean;
  error: string;
  feedbackErrorCode?: string;
  details?: unknown[];
  additionalProperties?: Record<string, unknown>;
}

export class FeedbackErrorResponseError extends ApiError<
  FeedbackErrorResponse
> {}
