/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Llmstxt404
 */
interface Llmstxt404 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Llmstxt404Error extends ApiError<Llmstxt404> {}
