/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Llmstxt400
 */
interface Llmstxt400 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Llmstxt400Error extends ApiError<Llmstxt400> {}
