/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Map402
 */
interface Map402 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Map402Error extends ApiError<Map402> {}
