/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Map429
 */
interface Map429 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Map429Error extends ApiError<Map429> {}
