/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Map500
 */
interface Map500 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Map500Error extends ApiError<Map500> {}
