/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Scrape402
 */
interface Scrape402 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Scrape402Error extends ApiError<Scrape402> {}
