/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Scrape429
 */
interface Scrape429 {
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Scrape429Error extends ApiError<Scrape429> {}
