/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Search408
 */
interface Search408 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Search408Error extends ApiError<Search408> {}
