/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Search500
 */
interface Search500 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class Search500Error extends ApiError<Search500> {}
