/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of TeamCreditUsage404
 */
interface TeamCreditUsage404 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class TeamCreditUsage404Error extends ApiError<TeamCreditUsage404> {}
