/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of TeamTokenUsage404
 */
interface TeamTokenUsage404 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class TeamTokenUsage404Error extends ApiError<TeamTokenUsage404> {}
