/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of TeamTokenUsage500
 */
interface TeamTokenUsage500 {
  success?: boolean;
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export class TeamTokenUsage500Error extends ApiError<TeamTokenUsage500> {}
