/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { Click, clickSchema } from '../click.js';
import {
  ExecuteJavaScript,
  executeJavaScriptSchema,
} from '../executeJavaScript.js';
import { PressAKey, pressAKeySchema } from '../pressAKey.js';
import { Scrape, scrapeSchema } from '../scrape.js';
import { Screenshot, screenshotSchema } from '../screenshot.js';
import { Scroll, scrollSchema } from '../scroll.js';
import { Wait, waitSchema } from '../wait.js';
import { WriteText, writeTextSchema } from '../writeText.js';

/** This is a container type for one-of types. */
export type ScrapeOptionsActions =
  | Wait
  | Screenshot
  | Click
  | WriteText
  | PressAKey
  | Scroll
  | Scrape
  | ExecuteJavaScript;

export const scrapeOptionsActionsSchema: Schema<ScrapeOptionsActions> = lazy(
  () =>
    oneOf([
      waitSchema,
      screenshotSchema,
      clickSchema,
      writeTextSchema,
      pressAKeySchema,
      scrollSchema,
      scrapeSchema,
      executeJavaScriptSchema,
    ])
);

export namespace ScrapeOptionsActions {
  /**
   * Validation method to narrow down union type to Wait type case.
   *
   * This is Wait case.
   */
  export function isWait(value: unknown): value is Wait {
    return isMappedValueValidForSchema(value, waitSchema);
  }

  /**
   * Validation method to narrow down union type to Screenshot type case.
   *
   * This is Screenshot case.
   */
  export function isScreenshot(value: unknown): value is Screenshot {
    return isMappedValueValidForSchema(value, screenshotSchema);
  }

  /**
   * Validation method to narrow down union type to Click type case.
   *
   * This is Click case.
   */
  export function isClick(value: unknown): value is Click {
    return isMappedValueValidForSchema(value, clickSchema);
  }

  /**
   * Validation method to narrow down union type to WriteText type case.
   *
   * This is Write text case.
   */
  export function isWriteText(value: unknown): value is WriteText {
    return isMappedValueValidForSchema(value, writeTextSchema);
  }

  /**
   * Validation method to narrow down union type to PressAKey type case.
   *
   * This is Press a key case.
   */
  export function isPressAKey(value: unknown): value is PressAKey {
    return isMappedValueValidForSchema(value, pressAKeySchema);
  }

  /**
   * Validation method to narrow down union type to Scroll type case.
   *
   * This is Scroll case.
   */
  export function isScroll(value: unknown): value is Scroll {
    return isMappedValueValidForSchema(value, scrollSchema);
  }

  /**
   * Validation method to narrow down union type to Scrape type case.
   *
   * This is Scrape case.
   */
  export function isScrape(value: unknown): value is Scrape {
    return isMappedValueValidForSchema(value, scrapeSchema);
  }

  /**
   * Validation method to narrow down union type to ExecuteJavaScript type case.
   *
   * This is Execute JavaScript case.
   */
  export function isExecuteJavaScript(
    value: unknown
  ): value is ExecuteJavaScript {
    return isMappedValueValidForSchema(value, executeJavaScriptSchema);
  }
}
