/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  TeamCreditUsageResponse,
  teamCreditUsageResponseSchema,
} from '../models/teamCreditUsageResponse.js';
import {
  TeamTokenUsageResponse,
  teamTokenUsageResponseSchema,
} from '../models/teamTokenUsageResponse.js';
import { BaseApi } from './baseApi.js';
import { TeamCreditUsage404Error } from '../errors/teamCreditUsage404Error.js';
import { TeamCreditUsage500Error } from '../errors/teamCreditUsage500Error.js';
import { TeamTokenUsage404Error } from '../errors/teamTokenUsage404Error.js';
import { TeamTokenUsage500Error } from '../errors/teamTokenUsage500Error.js';

export class BillingApi extends BaseApi {
  /**
   * @return Response from the API call
   */
  async getCreditUsage(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TeamCreditUsageResponse>> {
    const req = this.createRequest('GET', '/team/credit-usage');
    req.throwOn(
      404,
      TeamCreditUsage404Error,
      'Credit usage information not found'
    );
    req.throwOn(500, TeamCreditUsage500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(teamCreditUsageResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getTokenUsage(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TeamTokenUsageResponse>> {
    const req = this.createRequest('GET', '/team/token-usage');
    req.throwOn(
      404,
      TeamTokenUsage404Error,
      'Token usage information not found'
    );
    req.throwOn(500, TeamTokenUsage500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(teamTokenUsageResponseSchema, requestOptions);
  }
}
