/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CrawlActiveResponse,
  crawlActiveResponseSchema,
} from '../models/crawlActiveResponse.js';
import {
  CrawlErrorsResponseObj,
  crawlErrorsResponseObjSchema,
} from '../models/crawlErrorsResponseObj.js';
import { CrawlRequest, crawlRequestSchema } from '../models/crawlRequest.js';
import { CrawlResponse, crawlResponseSchema } from '../models/crawlResponse.js';
import {
  CrawlResponse1,
  crawlResponse1Schema,
} from '../models/crawlResponse1.js';
import {
  CrawlStatusResponseObj,
  crawlStatusResponseObjSchema,
} from '../models/crawlStatusResponseObj.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { Crawl402Error } from '../errors/crawl402Error.js';
import { Crawl404Error } from '../errors/crawl404Error.js';
import { Crawl429Error } from '../errors/crawl429Error.js';
import { Crawl500Error } from '../errors/crawl500Error.js';
import { CrawlActive402Error } from '../errors/crawlActive402Error.js';
import { CrawlActive429Error } from '../errors/crawlActive429Error.js';
import { CrawlActive500Error } from '../errors/crawlActive500Error.js';
import { CrawlErrors402Error } from '../errors/crawlErrors402Error.js';
import { CrawlErrors429Error } from '../errors/crawlErrors429Error.js';
import { CrawlErrors500Error } from '../errors/crawlErrors500Error.js';

export class CrawlingApi extends BaseApi {
  /**
   * @param id The ID of the crawl job
   * @return Response from the API call
   */
  async getCrawlStatus(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrawlStatusResponseObj>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/crawl/${mapped.id}`;
    req.throwOn(402, Crawl402Error, 'Payment required');
    req.throwOn(429, Crawl429Error, 'Too many requests');
    req.throwOn(500, Crawl500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(crawlStatusResponseObjSchema, requestOptions);
  }

  /**
   * @param id The ID of the crawl job
   * @return Response from the API call
   */
  async cancelCrawl(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrawlResponse1>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/crawl/${mapped.id}`;
    req.throwOn(404, Crawl404Error, 'Crawl job not found');
    req.throwOn(500, Crawl500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(crawlResponse1Schema, requestOptions);
  }

  /**
   * @param id The ID of the crawl job
   * @return Response from the API call
   */
  async getCrawlErrors(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrawlErrorsResponseObj>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/crawl/${mapped.id}/errors`;
    req.throwOn(402, CrawlErrors402Error, 'Payment required');
    req.throwOn(429, CrawlErrors429Error, 'Too many requests');
    req.throwOn(500, CrawlErrors500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(crawlErrorsResponseObjSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async crawlUrls(
    body: CrawlRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrawlResponse>> {
    const req = this.createRequest('POST', '/crawl');
    const mapped = req.prepareArgs({ body: [body, crawlRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(402, Crawl402Error, 'Payment required');
    req.throwOn(429, Crawl429Error, 'Too many requests');
    req.throwOn(500, Crawl500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(crawlResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getActiveCrawls(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrawlActiveResponse>> {
    const req = this.createRequest('GET', '/crawl/active');
    req.throwOn(402, CrawlActive402Error, 'Payment required');
    req.throwOn(429, CrawlActive429Error, 'Too many requests');
    req.throwOn(500, CrawlActive500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(crawlActiveResponseSchema, requestOptions);
  }
}
