/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ExtractRequest,
  extractRequestSchema,
} from '../models/extractRequest.js';
import {
  ExtractResponse,
  extractResponseSchema,
} from '../models/extractResponse.js';
import {
  ExtractStatusResponse,
  extractStatusResponseSchema,
} from '../models/extractStatusResponse.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { Extract400Error } from '../errors/extract400Error.js';
import { Extract500Error } from '../errors/extract500Error.js';

export class ExtractionApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async extractData(
    body: ExtractRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ExtractResponse>> {
    const req = this.createRequest('POST', '/extract');
    const mapped = req.prepareArgs({ body: [body, extractRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, Extract400Error, 'Invalid request');
    req.throwOn(500, Extract500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(extractResponseSchema, requestOptions);
  }

  /**
   * @param id The ID of the extract job
   * @return Response from the API call
   */
  async getExtractStatus(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ExtractStatusResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/extract/${mapped.id}`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(extractStatusResponseSchema, requestOptions);
  }
}
