/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  EndpointFeedbackRequest,
  endpointFeedbackRequestSchema,
} from '../models/endpointFeedbackRequest.js';
import {
  FeedbackResponse,
  feedbackResponseSchema,
} from '../models/feedbackResponse.js';
import { BaseApi } from './baseApi.js';
import { FeedbackErrorResponseError } from '../errors/feedbackErrorResponseError.js';

export class FeedbackApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async submitEndpointFeedback(
    body: EndpointFeedbackRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FeedbackResponse>> {
    const req = this.createRequest('POST', '/feedback');
    const mapped = req.prepareArgs({
      body: [body, endpointFeedbackRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, FeedbackErrorResponseError, 'Invalid request body');
    req.throwOn(
      403,
      FeedbackErrorResponseError,
      'Feedback is not available for this team'
    );
    req.throwOn(404, FeedbackErrorResponseError, 'Job not found for this team');
    req.throwOn(
      409,
      FeedbackErrorResponseError,
      'Feedback cannot be recorded for this job'
    );
    req.throwOn(500, FeedbackErrorResponseError, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(feedbackResponseSchema, requestOptions);
  }
}
