/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LlmstxtRequest,
  llmstxtRequestSchema,
} from '../models/llmstxtRequest.js';
import {
  LlmstxtResponse,
  llmstxtResponseSchema,
} from '../models/llmstxtResponse.js';
import {
  LlmstxtResponse1,
  llmstxtResponse1Schema,
} from '../models/llmstxtResponse1.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { Llmstxt400Error } from '../errors/llmstxt400Error.js';
import { Llmstxt404Error } from '../errors/llmstxt404Error.js';

export class LlMsTxtApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async generateLlMsTxt(
    body: LlmstxtRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LlmstxtResponse>> {
    const req = this.createRequest('POST', '/llmstxt');
    const mapped = req.prepareArgs({ body: [body, llmstxtRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, Llmstxt400Error, 'Invalid request parameters');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(llmstxtResponseSchema, requestOptions);
  }

  /**
   * @param id The ID of the LLMs.txt generation job
   * @return Response from the API call
   */
  async getLlMsTxtStatus(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LlmstxtResponse1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/llmstxt/${mapped.id}`;
    req.throwOn(404, Llmstxt404Error, 'LLMs.txt generation job not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(llmstxtResponse1Schema, requestOptions);
  }
}
