/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { MapRequest, mapRequestSchema } from '../models/mapRequest.js';
import { MapResponse, mapResponseSchema } from '../models/mapResponse.js';
import { BaseApi } from './baseApi.js';
import { Map402Error } from '../errors/map402Error.js';
import { Map429Error } from '../errors/map429Error.js';
import { Map500Error } from '../errors/map500Error.js';

export class MappingApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async mapUrls(
    body: MapRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MapResponse>> {
    const req = this.createRequest('POST', '/map');
    const mapped = req.prepareArgs({ body: [body, mapRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(402, Map402Error, 'Payment required');
    req.throwOn(429, Map429Error, 'Too many requests');
    req.throwOn(500, Map500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(mapResponseSchema, requestOptions);
  }
}
