/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DeepResearchRequest,
  deepResearchRequestSchema,
} from '../models/deepResearchRequest.js';
import {
  DeepResearchResponse,
  deepResearchResponseSchema,
} from '../models/deepResearchResponse.js';
import {
  DeepResearchResponse1,
  deepResearchResponse1Schema,
} from '../models/deepResearchResponse1.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DeepResearch400Error } from '../errors/deepResearch400Error.js';
import { DeepResearch404Error } from '../errors/deepResearch404Error.js';

export class ResearchApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async startDeepResearch(
    body: DeepResearchRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeepResearchResponse>> {
    const req = this.createRequest('POST', '/deep-research');
    const mapped = req.prepareArgs({ body: [body, deepResearchRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, DeepResearch400Error, 'Invalid request parameters');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(deepResearchResponseSchema, requestOptions);
  }

  /**
   * @param id The ID of the research job
   * @return Response from the API call
   */
  async getDeepResearchStatus(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeepResearchResponse1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/deep-research/${mapped.id}`;
    req.throwOn(404, DeepResearch404Error, 'Research job not found');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(deepResearchResponse1Schema, requestOptions);
  }
}
