/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BatchScrapeRequest,
  batchScrapeRequestSchema,
} from '../models/batchScrapeRequest.js';
import {
  BatchScrapeResponse,
  batchScrapeResponseSchema,
} from '../models/batchScrapeResponse.js';
import {
  BatchScrapeResponseObj,
  batchScrapeResponseObjSchema,
} from '../models/batchScrapeResponseObj.js';
import {
  BatchScrapeStatusResponseObj,
  batchScrapeStatusResponseObjSchema,
} from '../models/batchScrapeStatusResponseObj.js';
import {
  CrawlErrorsResponseObj,
  crawlErrorsResponseObjSchema,
} from '../models/crawlErrorsResponseObj.js';
import { ScrapeRequest, scrapeRequestSchema } from '../models/scrapeRequest.js';
import {
  ScrapeResponse,
  scrapeResponseSchema,
} from '../models/scrapeResponse.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { BatchScrape402Error } from '../errors/batchScrape402Error.js';
import { BatchScrape404Error } from '../errors/batchScrape404Error.js';
import { BatchScrape429Error } from '../errors/batchScrape429Error.js';
import { BatchScrape500Error } from '../errors/batchScrape500Error.js';
import { BatchScrapeErrors402Error } from '../errors/batchScrapeErrors402Error.js';
import { BatchScrapeErrors429Error } from '../errors/batchScrapeErrors429Error.js';
import { BatchScrapeErrors500Error } from '../errors/batchScrapeErrors500Error.js';
import { Scrape402Error } from '../errors/scrape402Error.js';
import { Scrape429Error } from '../errors/scrape429Error.js';
import { Scrape500Error } from '../errors/scrape500Error.js';

export class ScrapingApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async scrapeAndExtractFromUrl(
    body: ScrapeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ScrapeResponse>> {
    const req = this.createRequest('POST', '/scrape');
    const mapped = req.prepareArgs({ body: [body, scrapeRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(402, Scrape402Error, 'Payment required');
    req.throwOn(429, Scrape429Error, 'Too many requests');
    req.throwOn(500, Scrape500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(scrapeResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async scrapeAndExtractFromUrls(
    body: BatchScrapeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BatchScrapeResponseObj>> {
    const req = this.createRequest('POST', '/batch/scrape');
    const mapped = req.prepareArgs({ body: [body, batchScrapeRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(402, BatchScrape402Error, 'Payment required');
    req.throwOn(429, BatchScrape429Error, 'Too many requests');
    req.throwOn(500, BatchScrape500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(batchScrapeResponseObjSchema, requestOptions);
  }

  /**
   * @param id The ID of the batch scrape job
   * @return Response from the API call
   */
  async getBatchScrapeStatus(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BatchScrapeStatusResponseObj>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/batch/scrape/${mapped.id}`;
    req.throwOn(402, BatchScrape402Error, 'Payment required');
    req.throwOn(429, BatchScrape429Error, 'Too many requests');
    req.throwOn(500, BatchScrape500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(batchScrapeStatusResponseObjSchema, requestOptions);
  }

  /**
   * @param id The ID of the batch scrape job
   * @return Response from the API call
   */
  async cancelBatchScrape(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BatchScrapeResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/batch/scrape/${mapped.id}`;
    req.throwOn(404, BatchScrape404Error, 'Batch scrape job not found');
    req.throwOn(500, BatchScrape500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(batchScrapeResponseSchema, requestOptions);
  }

  /**
   * @param id The ID of the batch scrape job
   * @return Response from the API call
   */
  async getBatchScrapeErrors(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrawlErrorsResponseObj>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/batch/scrape/${mapped.id}/errors`;
    req.throwOn(402, BatchScrapeErrors402Error, 'Payment required');
    req.throwOn(429, BatchScrapeErrors429Error, 'Too many requests');
    req.throwOn(500, BatchScrapeErrors500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(crawlErrorsResponseObjSchema, requestOptions);
  }
}
