/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  FeedbackResponse,
  feedbackResponseSchema,
} from '../models/feedbackResponse.js';
import {
  SearchFeedbackRequest,
  searchFeedbackRequestSchema,
} from '../models/searchFeedbackRequest.js';
import { SearchRequest, searchRequestSchema } from '../models/searchRequest.js';
import {
  SearchResponse,
  searchResponseSchema,
} from '../models/searchResponse.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { FeedbackErrorResponseError } from '../errors/feedbackErrorResponseError.js';
import { Search408Error } from '../errors/search408Error.js';
import { Search500Error } from '../errors/search500Error.js';

export class SearchApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async searchAndScrape(
    body: SearchRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SearchResponse>> {
    const req = this.createRequest('POST', '/search');
    const mapped = req.prepareArgs({ body: [body, searchRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(408, Search408Error, 'Request timeout');
    req.throwOn(500, Search500Error, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(searchResponseSchema, requestOptions);
  }

  /**
   * @param jobId        Search job id returned by /search.
   * @param body
   * @return Response from the API call
   */
  async submitSearchFeedback(
    jobId: string,
    body: SearchFeedbackRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FeedbackResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      jobId: [jobId, string()],
      body: [body, searchFeedbackRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/search/${mapped.jobId}/feedback`;
    req.throwOn(400, FeedbackErrorResponseError, 'Invalid request body');
    req.throwOn(
      403,
      FeedbackErrorResponseError,
      'Feedback is not available for this team'
    );
    req.throwOn(
      404,
      FeedbackErrorResponseError,
      'Search not found for this team'
    );
    req.throwOn(
      409,
      FeedbackErrorResponseError,
      'Feedback cannot be recorded for this search'
    );
    req.throwOn(500, FeedbackErrorResponseError, 'Server error');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(feedbackResponseSchema, requestOptions);
  }
}
