/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  JavascriptReturn,
  javascriptReturnSchema,
} from './javascriptReturn.js';
import { Scrape1, scrape1Schema } from './scrape1.js';

/** Results of the actions specified in the `actions` parameter. Only present if the `actions` parameter was provided in the request */
export interface Actions {
  /** Screenshot URLs, in the same order as the screenshot actions provided. */
  screenshots?: string[];
  /** Scrape contents, in the same order as the scrape actions provided. */
  scrapes?: Scrape1[];
  /** JavaScript return values, in the same order as the executeJavascript actions provided. */
  javascriptReturns?: JavascriptReturn[];
  additionalProperties?: Record<string, unknown>;
}

export const actionsSchema: Schema<Actions> = lazy(() =>
  typedExpandoObject(
    {
      screenshots: ['screenshots', optional(array(string()))],
      scrapes: ['scrapes', optional(array(scrape1Schema))],
      javascriptReturns: [
        'javascriptReturns',
        optional(array(javascriptReturnSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
