/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Activity {
  type?: string;
  status?: string;
  message?: string;
  timestamp?: string;
  depth?: number;
  additionalProperties?: Record<string, unknown>;
}

export const activitySchema: Schema<Activity> = typedExpandoObject(
  {
    type: ['type', optional(string())],
    status: ['status', optional(string())],
    message: ['message', optional(string())],
    timestamp: ['timestamp', optional(string())],
    depth: ['depth', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
