/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data1, data1Schema } from './data1.js';

export interface BatchScrapeStatusResponseObj {
  /** The current status of the batch scrape. Can be `scraping`, `completed`, or `failed`. */
  status?: string;
  /** The total number of pages that were attempted to be scraped. */
  total?: number;
  /** The number of pages that have been successfully scraped. */
  completed?: number;
  /** The number of credits used for the batch scrape. */
  creditsUsed?: number;
  /** The date and time when the batch scrape will expire. */
  expiresAt?: string;
  /** The URL to retrieve the next 10MB of data. Returned if the batch scrape is not completed or if the response is larger than 10MB. */
  next?: string | null;
  /** The data of the batch scrape. */
  data?: Data1[];
  additionalProperties?: Record<string, unknown>;
}

export const batchScrapeStatusResponseObjSchema: Schema<BatchScrapeStatusResponseObj> = lazy(
  () =>
    typedExpandoObject(
      {
        status: ['status', optional(string())],
        total: ['total', optional(number())],
        completed: ['completed', optional(number())],
        creditsUsed: ['creditsUsed', optional(number())],
        expiresAt: ['expiresAt', optional(string())],
        next: ['next', optional(nullable(string()))],
        data: ['data', optional(array(data1Schema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
