/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BatchScrapeResponseObj {
  success?: boolean;
  id?: string;
  url?: string;
  /** If ignoreInvalidURLs is true, this is an array containing the invalid URLs that were specified in the request. If there were no invalid URLs, this will be an empty array. If ignoreInvalidURLs is false, this field will be undefined. */
  invalidUrLs?: string[] | null;
  additionalProperties?: Record<string, unknown>;
}

export const batchScrapeResponseObjSchema: Schema<BatchScrapeResponseObj> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    id: ['id', optional(string())],
    url: ['url', optional(string())],
    invalidUrLs: ['invalidURLs', optional(nullable(array(string())))],
  },
  'additionalProperties',
  optional(unknown())
);
