/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BatchScrapeResponse {
  success?: boolean;
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export const batchScrapeResponseSchema: Schema<BatchScrapeResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    message: ['message', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
