/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Font, fontSchema } from './font.js';

/** Brand identity information derived from executing on-page javascript. */
export interface Branding {
  /** Primary logo URL if detected. */
  logo?: string | null;
  /** Detected font families. */
  fonts?: Font[];
  colors?: unknown;
  typography?: unknown;
  spacing?: unknown;
  components?: unknown;
  icons?: unknown;
  images?: unknown;
  animations?: unknown;
  layout?: unknown;
  tone?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const brandingSchema: Schema<Branding> = lazy(() =>
  typedExpandoObject(
    {
      logo: ['logo', optional(nullable(string()))],
      fonts: ['fonts', optional(array(fontSchema))],
      colors: ['colors', optional(unknown())],
      typography: ['typography', optional(unknown())],
      spacing: ['spacing', optional(unknown())],
      components: ['components', optional(unknown())],
      icons: ['icons', optional(unknown())],
      images: ['images', optional(unknown())],
      animations: ['animations', optional(unknown())],
      layout: ['layout', optional(unknown())],
      tone: ['tone', optional(unknown())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
