/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Mode, modeSchema } from './mode.js';

/** Options for change tracking (Beta). Only applicable when 'changeTracking' is included in formats. The 'markdown' format must also be specified when using change tracking. */
export interface ChangeTrackingOptions {
  /** The mode to use for change tracking. 'git-diff' provides a detailed diff, and 'json' compares extracted JSON data. */
  modes?: Mode[];
  /** Schema for JSON extraction when using 'json' mode. Defines the structure of data to extract and compare. Must conform to [JSON Schema](https://json-schema.org/). */
  schema?: unknown;
  /** Prompt to use for change tracking when using 'json' mode. If not provided, the default prompt will be used. */
  prompt?: string;
  /** Tag to use for change tracking. Tags can separate change tracking history into separate "branches", where change tracking with a specific tagwill only compare to scrapes made in the same tag. If not provided, the default tag (null) will be used. */
  tag?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const changeTrackingOptionsSchema: Schema<ChangeTrackingOptions> = typedExpandoObject(
  {
    modes: ['modes', optional(array(modeSchema))],
    schema: ['schema', optional(unknown())],
    prompt: ['prompt', optional(string())],
    tag: ['tag', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
