/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChangeStatus, changeStatusSchema } from './changeStatus.js';
import { Visibility, visibilitySchema } from './visibility.js';

/** Change tracking information if `changeTracking` is in `formats`. Only present when the `changeTracking` format is requested. */
export interface ChangeTracking {
  /** The timestamp of the previous scrape that the current page is being compared against. Null if no previous scrape exists. */
  previousScrapeAt?: string | null;
  /** The result of the comparison between the two page versions. 'new' means this page did not exist before, 'same' means content has not changed, 'changed' means content has changed, 'removed' means the page was removed. */
  changeStatus?: ChangeStatus;
  /** The visibility of the current page/URL. 'visible' means the URL was discovered through an organic route (links or sitemap), 'hidden' means the URL was discovered through memory from previous crawls. */
  visibility?: Visibility;
  /** Git-style diff of changes when using 'git-diff' mode. Only present when the mode is set to 'git-diff'. */
  diff?: string | null;
  /** JSON comparison results when using 'json' mode. Only present when the mode is set to 'json'. This will emit a list of all the keys and their values from the `previous` and `current` scrapes based on the type defined in the `schema`. Example [here](/features/change-tracking) */
  json?: unknown | null;
  additionalProperties?: Record<string, unknown>;
}

export const changeTrackingSchema: Schema<ChangeTracking> = typedExpandoObject(
  {
    previousScrapeAt: ['previousScrapeAt', optional(nullable(string()))],
    changeStatus: ['changeStatus', optional(changeStatusSchema)],
    visibility: ['visibility', optional(visibilitySchema)],
    diff: ['diff', optional(nullable(string()))],
    json: ['json', optional(nullable(unknown()))],
  },
  'additionalProperties',
  optional(unknown())
);
