/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ChangeStatus
 */
export enum ChangeStatus {
  New = 'new',
  Same = 'same',
  Changed = 'changed',
  Removed = 'removed',
}

/**
 * Schema for ChangeStatus
 */
export const changeStatusSchema: Schema<ChangeStatus> = stringEnum(
  ChangeStatus
);
