/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type2, type2Schema } from './type2.js';

export interface Click {
  /** Click on an element */
  type: Type2;
  /** Query selector to find the element by */
  selector: string;
  /** Clicks all elements matched by the selector, not just the first one. Does not throw an error if no elements match the selector. */
  all?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const clickSchema: Schema<Click> = typedExpandoObject(
  {
    type: ['type', type2Schema],
    selector: ['selector', string()],
    all: ['all', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
