/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CrawlResponse {
  success?: boolean;
  id?: string;
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const crawlResponseSchema: Schema<CrawlResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    id: ['id', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
