/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error, errorSchema } from './error.js';

export interface CrawlErrorsResponseObj {
  /** Errored scrape jobs and error details */
  errors?: Error[];
  /** List of URLs that were attempted in scraping but were blocked by robots.txt */
  robotsBlocked?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const crawlErrorsResponseObjSchema: Schema<CrawlErrorsResponseObj> = lazy(
  () =>
    typedExpandoObject(
      {
        errors: ['errors', optional(array(errorSchema))],
        robotsBlocked: ['robotsBlocked', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
