/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data1, data1Schema } from './data1.js';

export interface CrawlStatusResponseObj {
  /** The current status of the crawl. Can be `scraping`, `completed`, or `failed`. */
  status?: string;
  /** The total number of pages that were attempted to be crawled. */
  total?: number;
  /** The number of pages that have been successfully crawled. */
  completed?: number;
  /** The number of credits used for the crawl. */
  creditsUsed?: number;
  /** The date and time when the crawl will expire. */
  expiresAt?: string;
  /** The date and time when the crawl was started. */
  createdAt?: string;
  /** The date and time when the crawl finished. Present only when the crawl is in a terminal state (`completed`, `failed`, or `cancelled`). */
  completedAt?: string;
  /** Crawl duration in seconds. For terminal crawls, this is the elapsed time from `createdAt` to `completedAt`. For in-progress crawls, it is the elapsed time from `createdAt` to now. */
  duration?: number;
  /** The URL to retrieve the next 10MB of data. Returned if the crawl is not completed or if the response is larger than 10MB. */
  next?: string | null;
  /** The data of the crawl. */
  data?: Data1[];
  additionalProperties?: Record<string, unknown>;
}

export const crawlStatusResponseObjSchema: Schema<CrawlStatusResponseObj> = lazy(
  () =>
    typedExpandoObject(
      {
        status: ['status', optional(string())],
        total: ['total', optional(number())],
        completed: ['completed', optional(number())],
        creditsUsed: ['creditsUsed', optional(number())],
        expiresAt: ['expiresAt', optional(string())],
        createdAt: ['createdAt', optional(string())],
        completedAt: ['completedAt', optional(string())],
        duration: ['duration', optional(number())],
        next: ['next', optional(nullable(string()))],
        data: ['data', optional(array(data1Schema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
