/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ScrapeOptions, scrapeOptionsSchema } from './scrapeOptions.js';
import { Webhook1, webhook1Schema } from './webhook1.js';

export interface CrawlRequest {
  /** The base URL to start crawling from */
  url: string;
  /** URL pathname regex patterns that exclude matching URLs from the crawl. For example, if you set "excludePaths": ["blog/.*"] for the base URL firecrawl.dev, any results matching that pattern will be excluded, such as https://www.firecrawl.dev/blog/firecrawl-launch-week-1-recap. */
  excludePaths?: string[];
  /** URL pathname regex patterns that include matching URLs in the crawl. Only the paths that match the specified patterns will be included in the response. For example, if you set "includePaths": ["blog/.*"] for the base URL firecrawl.dev, only results matching that pattern will be included, such as https://www.firecrawl.dev/blog/firecrawl-launch-week-1-recap. */
  includePaths?: string[];
  /** Maximum depth to crawl relative to the base URL. Basically, the max number of slashes the pathname of a scraped URL may contain. */
  maxDepth?: number;
  /** Maximum depth to crawl based on discovery order. The root site and sitemapped pages has a discovery depth of 0. For example, if you set it to 1, and you set ignoreSitemap, you will only crawl the entered URL and all URLs that are linked on that page. */
  maxDiscoveryDepth?: number;
  /** Ignore the website sitemap when crawling */
  ignoreSitemap?: boolean;
  /** Do not re-scrape the same path with different (or none) query parameters */
  ignoreQueryParameters?: boolean;
  /** Maximum number of pages to crawl. Default limit is 10000. */
  limit?: number;
  /**
   * Allows the crawler to follow internal links to sibling or parent URLs, not just child paths.
   * false: Only crawls deeper (child) URLs.
   * → e.g. /features/feature-1 → /features/feature-1/tips ✅
   * → Won't follow /pricing or / ❌
   * true: Crawls any internal links, including siblings and parents.
   * → e.g. /features/feature-1 → /pricing, /, etc. ✅
   * Use true for broader internal coverage beyond nested paths.
   */
  allowBackwardLinks?: boolean;
  /** Allows the crawler to follow links to external websites. */
  allowExternalLinks?: boolean;
  /** Delay in seconds between scrapes. This helps respect website rate limits. */
  delay?: number;
  /** A webhook specification object. */
  webhook?: Webhook1;
  scrapeOptions?: ScrapeOptions;
  additionalProperties?: Record<string, unknown>;
}

export const crawlRequestSchema: Schema<CrawlRequest> = lazy(() =>
  typedExpandoObject(
    {
      url: ['url', string()],
      excludePaths: ['excludePaths', optional(array(string()))],
      includePaths: ['includePaths', optional(array(string()))],
      maxDepth: ['maxDepth', optional(number())],
      maxDiscoveryDepth: ['maxDiscoveryDepth', optional(number())],
      ignoreSitemap: ['ignoreSitemap', optional(boolean())],
      ignoreQueryParameters: ['ignoreQueryParameters', optional(boolean())],
      limit: ['limit', optional(number())],
      allowBackwardLinks: ['allowBackwardLinks', optional(boolean())],
      allowExternalLinks: ['allowExternalLinks', optional(boolean())],
      delay: ['delay', optional(number())],
      webhook: ['webhook', optional(webhook1Schema)],
      scrapeOptions: ['scrapeOptions', optional(scrapeOptionsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
