/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { Status1, status1Schema } from './status1.js';

export interface CrawlResponse1 {
  status?: Status1;
  additionalProperties?: Record<string, unknown>;
}

export const crawlResponse1Schema: Schema<CrawlResponse1> = typedExpandoObject(
  { status: ['status', optional(status1Schema)] },
  'additionalProperties',
  optional(unknown())
);
