/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Options, optionsSchema } from './options.js';

export interface Crawl {
  /** The unique identifier of the crawl */
  id: string;
  /** The ID of the team that owns the crawl */
  teamId: string;
  /** The origin URL of the crawl */
  url: string;
  /** The crawler options used for this crawl */
  options: Options;
  additionalProperties?: Record<string, unknown>;
}

export const crawlSchema: Schema<Crawl> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      teamId: ['teamId', string()],
      url: ['url', string()],
      options: ['options', optionsSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
