/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Crawl, crawlSchema } from './crawl.js';

export interface CrawlActiveResponse {
  success: boolean;
  crawls?: Crawl[];
  additionalProperties?: Record<string, unknown>;
}

export const crawlActiveResponseSchema: Schema<CrawlActiveResponse> = lazy(() =>
  typedExpandoObject(
    {
      success: ['success', boolean()],
      crawls: ['crawls', optional(array(crawlSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
