/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Metadata3, metadata3Schema } from './metadata3.js';

export interface Data6 {
  /** Title from search result */
  title?: string;
  /** Description from search result */
  description?: string;
  /** URL of the search result */
  url?: string;
  /** Markdown content if scraping was requested */
  markdown?: string | null;
  /** HTML content if requested in formats */
  html?: string | null;
  /** Raw HTML content if requested in formats */
  rawHtml?: string | null;
  /** Links found if requested in formats */
  links?: string[];
  /** Screenshot URL if requested in formats */
  screenshot?: string | null;
  metadata?: Metadata3;
  additionalProperties?: Record<string, unknown>;
}

export const data6Schema: Schema<Data6> = lazy(() =>
  typedExpandoObject(
    {
      title: ['title', optional(string())],
      description: ['description', optional(string())],
      url: ['url', optional(string())],
      markdown: ['markdown', optional(nullable(string()))],
      html: ['html', optional(nullable(string()))],
      rawHtml: ['rawHtml', optional(nullable(string()))],
      links: ['links', optional(array(string()))],
      screenshot: ['screenshot', optional(nullable(string()))],
      metadata: ['metadata', optional(metadata3Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
