/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Metadata, metadataSchema } from './metadata.js';

export interface Data1 {
  markdown?: string;
  /** HTML version of the content on page if `includeHtml`  is true */
  html?: string | null;
  /** Raw HTML content of the page if `includeRawHtml`  is true */
  rawHtml?: string | null;
  /** List of links on the page if `includeLinks` is true */
  links?: string[];
  /** Screenshot of the page if `includeScreenshot` is true */
  screenshot?: string | null;
  metadata?: Metadata;
  additionalProperties?: Record<string, unknown>;
}

export const data1Schema: Schema<Data1> = lazy(() =>
  typedExpandoObject(
    {
      markdown: ['markdown', optional(string())],
      html: ['html', optional(nullable(string()))],
      rawHtml: ['rawHtml', optional(nullable(string()))],
      links: ['links', optional(array(string()))],
      screenshot: ['screenshot', optional(nullable(string()))],
      metadata: ['metadata', optional(metadataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
