/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data7 {
  /** The generated LLMs.txt content */
  llmstxt?: string;
  /** The full text content when showFullText is true */
  llmsfulltxt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const data7Schema: Schema<Data7> = typedExpandoObject(
  {
    llmstxt: ['llmstxt', optional(string())],
    llmsfulltxt: ['llmsfulltxt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
