/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data5 {
  /** Number of tokens remaining for the team */
  remainingTokens?: number;
  additionalProperties?: Record<string, unknown>;
}

export const data5Schema: Schema<Data5> = typedExpandoObject(
  { remainingTokens: ['remaining_tokens', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
