/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data4 {
  /** Number of credits remaining for the team */
  remainingCredits?: number;
  additionalProperties?: Record<string, unknown>;
}

export const data4Schema: Schema<Data4> = typedExpandoObject(
  { remainingCredits: ['remaining_credits', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
