/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Activity, activitySchema } from './activity.js';
import { Source, sourceSchema } from './source.js';
import { Status2, status2Schema } from './status2.js';

export interface Data3 {
  finalAnalysis?: string;
  /** Displayed when using JSON format */
  json?: unknown | null;
  activities?: Activity[];
  sources?: Source[];
  status?: Status2;
  error?: string;
  expiresAt?: string;
  currentDepth?: number;
  maxDepth?: number;
  totalUrls?: number;
  additionalProperties?: Record<string, unknown>;
}

export const data3Schema: Schema<Data3> = lazy(() =>
  typedExpandoObject(
    {
      finalAnalysis: ['finalAnalysis', optional(string())],
      json: ['json', optional(nullable(unknown()))],
      activities: ['activities', optional(array(activitySchema))],
      sources: ['sources', optional(array(sourceSchema))],
      status: ['status', optional(status2Schema)],
      error: ['error', optional(string())],
      expiresAt: ['expiresAt', optional(string())],
      currentDepth: ['currentDepth', optional(number())],
      maxDepth: ['maxDepth', optional(number())],
      totalUrls: ['totalUrls', optional(number())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
