/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Actions, actionsSchema } from './actions.js';
import { Branding, brandingSchema } from './branding.js';
import { ChangeTracking, changeTrackingSchema } from './changeTracking.js';
import { Metadata, metadataSchema } from './metadata.js';

export interface Data {
  markdown?: string;
  /** HTML version of the content on page if `html` is in `formats` */
  html?: string | null;
  /** Raw HTML content of the page if `rawHtml` is in `formats` */
  rawHtml?: string | null;
  /** Screenshot of the page if `screenshot` is in `formats` */
  screenshot?: string | null;
  /** List of links on the page if `links` is in `formats` */
  links?: string[];
  /** Results of the actions specified in the `actions` parameter. Only present if the `actions` parameter was provided in the request */
  actions?: Actions | null;
  metadata?: Metadata;
  /** Displayed when using LLM Extraction. Extracted data from the page following the schema defined. */
  llmExtraction?: unknown | null;
  /** Can be displayed when using LLM Extraction. Warning message will let you know any issues with the extraction. */
  warning?: string | null;
  /** Change tracking information if `changeTracking` is in `formats`. Only present when the `changeTracking` format is requested. */
  changeTracking?: ChangeTracking | null;
  /** Brand identity information derived from executing on-page javascript. */
  branding?: Branding | null;
  additionalProperties?: Record<string, unknown>;
}

export const dataSchema: Schema<Data> = lazy(() =>
  typedExpandoObject(
    {
      markdown: ['markdown', optional(string())],
      html: ['html', optional(nullable(string()))],
      rawHtml: ['rawHtml', optional(nullable(string()))],
      screenshot: ['screenshot', optional(nullable(string()))],
      links: ['links', optional(array(string()))],
      actions: ['actions', optional(nullable(actionsSchema))],
      metadata: ['metadata', optional(metadataSchema)],
      llmExtraction: ['llm_extraction', optional(nullable(unknown()))],
      warning: ['warning', optional(nullable(string()))],
      changeTracking: [
        'changeTracking',
        optional(nullable(changeTrackingSchema)),
      ],
      branding: ['branding', optional(nullable(brandingSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
