/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Format1, format1Schema } from './format1.js';
import { JsonOptions1, jsonOptions1Schema } from './jsonOptions1.js';

export interface DeepResearchRequest {
  /** The query to research */
  query: string;
  /** Maximum depth of research iterations */
  maxDepth?: number;
  /** Time limit in seconds */
  timeLimit?: number;
  /** Maximum number of URLs to analyze */
  maxUrls?: number;
  /** The prompt to use for the final analysis. Useful to format the final analysis markdown in a specific way. */
  analysisPrompt?: string;
  /** The system prompt to use for the research agent. Useful to steer the research agent to a specific direction. */
  systemPrompt?: string;
  formats?: Format1[];
  /** Options for JSON output */
  jsonOptions?: JsonOptions1;
  additionalProperties?: Record<string, unknown>;
}

export const deepResearchRequestSchema: Schema<DeepResearchRequest> = lazy(() =>
  typedExpandoObject(
    {
      query: ['query', string()],
      maxDepth: ['maxDepth', optional(number())],
      timeLimit: ['timeLimit', optional(number())],
      maxUrls: ['maxUrls', optional(number())],
      analysisPrompt: ['analysisPrompt', optional(string())],
      systemPrompt: ['systemPrompt', optional(string())],
      formats: ['formats', optional(array(format1Schema))],
      jsonOptions: ['jsonOptions', optional(jsonOptions1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
