/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DeepResearchResponse {
  success?: boolean;
  /** ID of the research job */
  id?: string;
  additionalProperties?: Record<string, unknown>;
}

export const deepResearchResponseSchema: Schema<DeepResearchResponse> = typedExpandoObject(
  { success: ['success', optional(boolean())], id: ['id', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
