/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data3, data3Schema } from './data3.js';

export interface DeepResearchResponse1 {
  success?: boolean;
  data?: Data3;
  additionalProperties?: Record<string, unknown>;
}

export const deepResearchResponse1Schema: Schema<DeepResearchResponse1> = lazy(
  () =>
    typedExpandoObject(
      {
        success: ['success', optional(boolean())],
        data: ['data', optional(data3Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
