/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction
 */
export enum Direction {
  Up = 'up',
  Down = 'down',
}

/**
 * Schema for Direction
 */
export const directionSchema: Schema<Direction> = stringEnum(Direction);
