/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Endpoint, endpointSchema } from './endpoint.js';
import { MissingContent, missingContentSchema } from './missingContent.js';
import { Rating, ratingSchema } from './rating.js';
import { ValuableSource, valuableSourceSchema } from './valuableSource.js';

export interface EndpointFeedbackRequest {
  rating: Rating;
  valuableSources?: ValuableSource[];
  missingContent?: MissingContent[];
  querySuggestions?: string;
  origin?: string;
  integration?: string | null;
  endpoint: Endpoint;
  jobId: string;
  issues?: string[];
  tags?: string[];
  note?: string;
  url?: string;
  pageNumbers?: number[];
  /** Small endpoint-specific metadata object. Must be 8KB or smaller; do not include full endpoint results. */
  metadata?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const endpointFeedbackRequestSchema: Schema<EndpointFeedbackRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        rating: ['rating', ratingSchema],
        valuableSources: [
          'valuableSources',
          optional(array(valuableSourceSchema)),
        ],
        missingContent: [
          'missingContent',
          optional(array(missingContentSchema)),
        ],
        querySuggestions: ['querySuggestions', optional(string())],
        origin: ['origin', optional(string())],
        integration: ['integration', optional(nullable(string()))],
        endpoint: ['endpoint', endpointSchema],
        jobId: ['jobId', string()],
        issues: ['issues', optional(array(string()))],
        tags: ['tags', optional(array(string()))],
        note: ['note', optional(string())],
        url: ['url', optional(string())],
        pageNumbers: ['pageNumbers', optional(array(number()))],
        metadata: ['metadata', optional(unknown())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
