/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Endpoint
 */
export enum Endpoint {
  Search = 'search',
  Scrape = 'scrape',
  Parse = 'parse',
  Map = 'map',
}

/**
 * Schema for Endpoint
 */
export const endpointSchema: Schema<Endpoint> = stringEnum(Endpoint);
