/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Error {
  id?: string;
  /** ISO timestamp of failure */
  timestamp?: string | null;
  /** Scraped URL */
  url?: string;
  /** Error message */
  error?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorSchema: Schema<Error> = typedExpandoObject(
  {
    id: ['id', optional(string())],
    timestamp: ['timestamp', optional(nullable(string()))],
    url: ['url', optional(string())],
    error: ['error', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
