/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Event
 */
export enum Event {
  Completed = 'completed',
  Page = 'page',
  Failed = 'failed',
  Started = 'started',
}

/**
 * Schema for Event
 */
export const eventSchema: Schema<Event> = stringEnum(Event);
