/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type7, type7Schema } from './type7.js';

export interface ExecuteJavaScript {
  /** Execute JavaScript code on the page */
  type: Type7;
  /** JavaScript code to execute */
  script: string;
  additionalProperties?: Record<string, unknown>;
}

export const executeJavaScriptSchema: Schema<ExecuteJavaScript> = typedExpandoObject(
  { type: ['type', type7Schema], script: ['script', string()] },
  'additionalProperties',
  optional(unknown())
);
