/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Status, statusSchema } from './status.js';

export interface ExtractStatusResponse {
  success?: boolean;
  data?: unknown;
  /** The current status of the extract job */
  status?: Status;
  expiresAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const extractStatusResponseSchema: Schema<ExtractStatusResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    data: ['data', optional(unknown())],
    status: ['status', optional(statusSchema)],
    expiresAt: ['expiresAt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
