/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ScrapeOptions, scrapeOptionsSchema } from './scrapeOptions.js';

export interface ExtractRequest {
  urls: string[];
  /** Prompt to guide the extraction process */
  prompt?: string;
  /** Schema to define the structure of the extracted data. Must conform to [JSON Schema](https://json-schema.org/). */
  schema?: unknown;
  /** When true, the extraction will use web search to find additional data */
  enableWebSearch?: boolean;
  /** When true, sitemap.xml files will be ignored during website scanning */
  ignoreSitemap?: boolean;
  /** When true, subdomains of the provided URLs will also be scanned */
  includeSubdomains?: boolean;
  /** When true, the sources used to extract the data will be included in the response as `sources` key */
  showSources?: boolean;
  scrapeOptions?: ScrapeOptions;
  /** If invalid URLs are specified in the urls array, they will be ignored. Instead of them failing the entire request, an extract using the remaining valid URLs will be performed, and the invalid URLs will be returned in the invalidURLs field of the response. */
  ignoreInvalidUrLs?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const extractRequestSchema: Schema<ExtractRequest> = lazy(() =>
  typedExpandoObject(
    {
      urls: ['urls', array(string())],
      prompt: ['prompt', optional(string())],
      schema: ['schema', optional(unknown())],
      enableWebSearch: ['enableWebSearch', optional(boolean())],
      ignoreSitemap: ['ignoreSitemap', optional(boolean())],
      includeSubdomains: ['includeSubdomains', optional(boolean())],
      showSources: ['showSources', optional(boolean())],
      scrapeOptions: ['scrapeOptions', optional(scrapeOptionsSchema)],
      ignoreInvalidUrLs: ['ignoreInvalidURLs', optional(boolean())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
