/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FeedbackResponse {
  success: boolean;
  feedbackId: string;
  creditsRefunded: number;
  alreadySubmitted?: boolean;
  dailyCapReached?: boolean;
  creditsRefundedToday?: number;
  dailyRefundCap?: number;
  warning?: string;
  additionalProperties?: Record<string, unknown>;
}

export const feedbackResponseSchema: Schema<FeedbackResponse> = typedExpandoObject(
  {
    success: ['success', boolean()],
    feedbackId: ['feedbackId', string()],
    creditsRefunded: ['creditsRefunded', number()],
    alreadySubmitted: ['alreadySubmitted', optional(boolean())],
    dailyCapReached: ['dailyCapReached', optional(boolean())],
    creditsRefundedToday: ['creditsRefundedToday', optional(number())],
    dailyRefundCap: ['dailyRefundCap', optional(number())],
    warning: ['warning', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
