/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Font {
  family?: string;
  additionalProperties?: Record<string, unknown>;
}

export const fontSchema: Schema<Font> = typedExpandoObject(
  { family: ['family', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
