/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Format
 */
export enum Format {
  Markdown = 'markdown',
  Html = 'html',
  RawHtml = 'rawHtml',
  Links = 'links',
  Screenshot = 'screenshot',
  EnumScreenshotfullPage = 'screenshot@fullPage',
  Json = 'json',
  ChangeTracking = 'changeTracking',
  Branding = 'branding',
}

/**
 * Schema for Format
 */
export const formatSchema: Schema<Format> = stringEnum(Format);
