/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Format1
 */
export enum Format1 {
  Markdown = 'markdown',
  Json = 'json',
  Branding = 'branding',
}

/**
 * Schema for Format1
 */
export const format1Schema: Schema<Format1> = stringEnum(Format1);
