/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Format2
 */
export enum Format2 {
  Markdown = 'markdown',
  Html = 'html',
  RawHtml = 'rawHtml',
  Links = 'links',
  Screenshot = 'screenshot',
  EnumScreenshotfullPage = 'screenshot@fullPage',
  Json = 'json',
  Branding = 'branding',
}

/**
 * Schema for Format2
 */
export const format2Schema: Schema<Format2> = stringEnum(Format2);
