/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface JavascriptReturn {
  type?: string;
  value?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const javascriptReturnSchema: Schema<JavascriptReturn> = typedExpandoObject(
  { type: ['type', optional(string())], value: ['value', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
