/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** JSON options object */
export interface JsonOptions {
  /** The schema to use for the extraction (Optional). Must conform to [JSON Schema](https://json-schema.org/). */
  schema?: unknown;
  /** The system prompt to use for the extraction (Optional) */
  systemPrompt?: string;
  /** The prompt to use for the extraction without a schema (Optional) */
  prompt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const jsonOptionsSchema: Schema<JsonOptions> = typedExpandoObject(
  {
    schema: ['schema', optional(unknown())],
    systemPrompt: ['systemPrompt', optional(string())],
    prompt: ['prompt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
