/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Options for JSON output */
export interface JsonOptions1 {
  /** The schema to use for the JSON output. Must conform to [JSON Schema](https://json-schema.org/). */
  schema?: unknown;
  /** The system prompt to use for the JSON output */
  systemPrompt?: string;
  /** The prompt to use for the JSON output */
  prompt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const jsonOptions1Schema: Schema<JsonOptions1> = typedExpandoObject(
  {
    schema: ['schema', optional(unknown())],
    systemPrompt: ['systemPrompt', optional(string())],
    prompt: ['prompt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
