/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data7, data7Schema } from './data7.js';
import { Status2, status2Schema } from './status2.js';

export interface LlmstxtResponse1 {
  success?: boolean;
  status?: Status2;
  data?: Data7;
  /** When the generated content will expire */
  expiresAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const llmstxtResponse1Schema: Schema<LlmstxtResponse1> = lazy(() =>
  typedExpandoObject(
    {
      success: ['success', optional(boolean())],
      status: ['status', optional(status2Schema)],
      data: ['data', optional(data7Schema)],
      expiresAt: ['expiresAt', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
