/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LlmstxtRequest {
  /** The URL to generate LLMs.txt from */
  url: string;
  /** Maximum number of URLs to analyze */
  maxUrls?: number;
  /** Include full text content in the response */
  showFullText?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const llmstxtRequestSchema: Schema<LlmstxtRequest> = typedExpandoObject(
  {
    url: ['url', string()],
    maxUrls: ['maxUrls', optional(number())],
    showFullText: ['showFullText', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
