/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Location settings for the request. When specified, this will use an appropriate proxy if available and emulate the corresponding language and timezone settings. Defaults to 'US' if not specified. */
export interface Location {
  /** ISO 3166-1 alpha-2 country code (e.g., 'US', 'AU', 'DE', 'JP') */
  country?: string;
  /** Preferred languages and locales for the request in order of priority. Defaults to the language of the specified location. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language */
  languages?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const locationSchema: Schema<Location> = typedExpandoObject(
  {
    country: ['country', optional(string())],
    languages: ['languages', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
