/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MapResponse {
  success?: boolean;
  /** The map job id. Use this as jobId when submitting feedback. */
  id?: string;
  links?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const mapResponseSchema: Schema<MapResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    id: ['id', optional(string())],
    links: ['links', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
