/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MapRequest {
  /** The base URL to start crawling from */
  url: string;
  /** Search query to use for mapping. During the Alpha phase, the 'smart' part of the search functionality is limited to 1000 search results. However, if map finds more results, there is no limit applied. */
  search?: string;
  /** Ignore the website sitemap when crawling. */
  ignoreSitemap?: boolean;
  /** Only return links found in the website sitemap */
  sitemapOnly?: boolean;
  /** Include subdomains of the website */
  includeSubdomains?: boolean;
  /** Maximum number of links to return */
  limit?: number;
  /** Timeout in milliseconds. There is no timeout by default. */
  timeout?: number;
  additionalProperties?: Record<string, unknown>;
}

export const mapRequestSchema: Schema<MapRequest> = typedExpandoObject(
  {
    url: ['url', string()],
    search: ['search', optional(string())],
    ignoreSitemap: ['ignoreSitemap', optional(boolean())],
    sitemapOnly: ['sitemapOnly', optional(boolean())],
    includeSubdomains: ['includeSubdomains', optional(boolean())],
    limit: ['limit', optional(number())],
    timeout: ['timeout', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
