/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Metadata {
  title?: string;
  description?: string;
  language?: string | null;
  sourceUrl?: string;
  mAnyOtherMetadata?: string;
  /** The status code of the page */
  statusCode?: number;
  /** Timezone inferred by the scraping engine, when available */
  timezone?: string;
  /** The error message of the page */
  error?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const metadataSchema: Schema<Metadata> = typedExpandoObject(
  {
    title: ['title', optional(string())],
    description: ['description', optional(string())],
    language: ['language', optional(nullable(string()))],
    sourceUrl: ['sourceURL', optional(string())],
    mAnyOtherMetadata: ['<any other metadata>', optional(string())],
    statusCode: ['statusCode', optional(number())],
    timezone: ['timezone', optional(string())],
    error: ['error', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
