/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Metadata3 {
  title?: string;
  description?: string;
  sourceUrl?: string;
  statusCode?: number;
  error?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const metadata3Schema: Schema<Metadata3> = typedExpandoObject(
  {
    title: ['title', optional(string())],
    description: ['description', optional(string())],
    sourceUrl: ['sourceURL', optional(string())],
    statusCode: ['statusCode', optional(number())],
    error: ['error', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
