/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MissingContent {
  topic: string;
  description?: string;
  additionalProperties?: Record<string, unknown>;
}

export const missingContentSchema: Schema<MissingContent> = typedExpandoObject(
  {
    topic: ['topic', string()],
    description: ['description', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
