/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ScrapeOptions, scrapeOptionsSchema } from './scrapeOptions.js';

/** The crawler options used for this crawl */
export interface Options {
  scrapeOptions?: ScrapeOptions;
  additionalProperties?: Record<string, unknown>;
}

export const optionsSchema: Schema<Options> = lazy(() =>
  typedExpandoObject(
    { scrapeOptions: ['scrapeOptions', optional(scrapeOptionsSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
