/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type4, type4Schema } from './type4.js';

/** Press a key on the page. See https://asawicki.info/nosense/doc/devices/keyboard/key_codes.html for key codes. */
export interface PressAKey {
  /** Press a key on the page */
  type: Type4;
  /** Key to press */
  key: string;
  additionalProperties?: Record<string, unknown>;
}

export const pressAKeySchema: Schema<PressAKey> = typedExpandoObject(
  { type: ['type', type4Schema], key: ['key', string()] },
  'additionalProperties',
  optional(unknown())
);
