/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Proxy
 */
export enum Proxy {
  Basic = 'basic',
  Enhanced = 'enhanced',
  Auto = 'auto',
}

/**
 * Schema for Proxy
 */
export const proxySchema: Schema<Proxy> = stringEnum(Proxy);
