/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data, dataSchema } from './data.js';

export interface ScrapeResponse {
  success?: boolean;
  data?: Data;
  additionalProperties?: Record<string, unknown>;
}

export const scrapeResponseSchema: Schema<ScrapeResponse> = lazy(() =>
  typedExpandoObject(
    {
      success: ['success', optional(boolean())],
      data: ['data', optional(dataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
