/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Format2, format2Schema } from './format2.js';

/** Options for scraping search results */
export interface ScrapeOptions1 {
  /** Formats to include in the output */
  formats?: Format2[];
  additionalProperties?: Record<string, unknown>;
}

export const scrapeOptions1Schema: Schema<ScrapeOptions1> = typedExpandoObject(
  { formats: ['formats', optional(array(format2Schema))] },
  'additionalProperties',
  optional(unknown())
);
