/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChangeTrackingOptions,
  changeTrackingOptionsSchema,
} from './changeTrackingOptions.js';
import {
  ScrapeOptionsActions,
  scrapeOptionsActionsSchema,
} from './containers/scrapeOptionsActions.js';
import { Format, formatSchema } from './format.js';
import { JsonOptions, jsonOptionsSchema } from './jsonOptions.js';
import { Location, locationSchema } from './location.js';
import { Proxy, proxySchema } from './proxy.js';

export interface ScrapeOptions {
  /** Formats to include in the output. */
  formats?: Format[];
  /** Only return the main content of the page excluding headers, navs, footers, etc. */
  onlyMainContent?: boolean;
  /** Tags to include in the output. */
  includeTags?: string[];
  /** Tags to exclude from the output. */
  excludeTags?: string[];
  /** Returns a cached version of the page if it is younger than this age in milliseconds. If a cached version of the page is older than this value, the page will be scraped. If you do not need extremely fresh data, enabling this can speed up your scrapes by 500%. Defaults to 0, which disables caching. */
  maxAge?: number;
  /** Headers to send with the request. Can be used to send cookies, user-agent, etc. */
  headers?: unknown;
  /** Specify a delay in milliseconds before fetching the content, allowing the page sufficient time to load. */
  waitFor?: number;
  /** Set to true if you want to emulate scraping from a mobile device. Useful for testing responsive pages and taking mobile screenshots. */
  mobile?: boolean;
  /** Skip TLS certificate verification when making requests */
  skipTlsVerification?: boolean;
  /** Timeout in milliseconds for the request */
  timeout?: number;
  /** Controls how PDF files are processed during scraping. When true, the PDF content is extracted and converted to markdown format, with billing based on the number of pages (1 credit per page). When false, the PDF file is returned in base64 encoding with a flat rate of 1 credit total. */
  parsePdf?: boolean;
  /** JSON options object */
  jsonOptions?: JsonOptions;
  /** Actions to perform on the page before grabbing the content */
  actions?: ScrapeOptionsActions[];
  /** Location settings for the request. When specified, this will use an appropriate proxy if available and emulate the corresponding language and timezone settings. Defaults to 'US' if not specified. */
  location?: Location;
  /** Removes all base 64 images from the output, which may be overwhelmingly long. The image's alt text remains in the output, but the URL is replaced with a placeholder. */
  removeBase64Images?: boolean;
  /** Enables ad-blocking and cookie popup blocking. */
  blockAds?: boolean;
  /**
   * Specifies the type of proxy to use.
   *  - **basic**: Proxies for scraping sites with none to basic anti-bot solutions. Fast and usually works.
   *  - **enhanced**: Enhanced proxies for scraping sites with advanced anti-bot solutions. Slower, but more reliable on certain sites. Costs up to 5 credits per request.
   *  - **auto**: Firecrawl will automatically retry scraping with enhanced proxies if the basic proxy fails. If the retry with enhanced is successful, 5 credits will be billed for the scrape. If the first attempt with basic is successful, only the regular cost will be billed.
   * If you do not specify a proxy, Firecrawl will default to basic.
   */
  proxy?: Proxy;
  /** Options for change tracking (Beta). Only applicable when 'changeTracking' is included in formats. The 'markdown' format must also be specified when using change tracking. */
  changeTrackingOptions?: ChangeTrackingOptions;
  /** If true, the page will be stored in the Firecrawl index and cache. Setting this to false is useful if your scraping activity may have data protection concerns. Using some parameters associated with sensitive scraping (actions, headers) will force this parameter to be false. */
  storeInCache?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const scrapeOptionsSchema: Schema<ScrapeOptions> = lazy(() =>
  typedExpandoObject(
    {
      formats: ['formats', optional(array(formatSchema))],
      onlyMainContent: ['onlyMainContent', optional(boolean())],
      includeTags: ['includeTags', optional(array(string()))],
      excludeTags: ['excludeTags', optional(array(string()))],
      maxAge: ['maxAge', optional(number())],
      headers: ['headers', optional(unknown())],
      waitFor: ['waitFor', optional(number())],
      mobile: ['mobile', optional(boolean())],
      skipTlsVerification: ['skipTlsVerification', optional(boolean())],
      timeout: ['timeout', optional(number())],
      parsePdf: ['parsePDF', optional(boolean())],
      jsonOptions: ['jsonOptions', optional(jsonOptionsSchema)],
      actions: ['actions', optional(array(scrapeOptionsActionsSchema))],
      location: ['location', optional(locationSchema)],
      removeBase64Images: ['removeBase64Images', optional(boolean())],
      blockAds: ['blockAds', optional(boolean())],
      proxy: ['proxy', optional(proxySchema)],
      changeTrackingOptions: [
        'changeTrackingOptions',
        optional(changeTrackingOptionsSchema),
      ],
      storeInCache: ['storeInCache', optional(boolean())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
