/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Scrape1 {
  url?: string;
  html?: string;
  additionalProperties?: Record<string, unknown>;
}

export const scrape1Schema: Schema<Scrape1> = typedExpandoObject(
  { url: ['url', optional(string())], html: ['html', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
