/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { Type6, type6Schema } from './type6.js';

export interface Scrape {
  /** Scrape the current page content, returns the url and the html. */
  type: Type6;
  additionalProperties?: Record<string, unknown>;
}

export const scrapeSchema: Schema<Scrape> = typedExpandoObject(
  { type: ['type', type6Schema] },
  'additionalProperties',
  optional(unknown())
);
