/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type1, type1Schema } from './type1.js';

export interface Screenshot {
  /** Take a screenshot. The links will be in the response's `actions.screenshots` array. */
  type: Type1;
  /** Should the screenshot be full-page or viewport sized? */
  fullPage?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const screenshotSchema: Schema<Screenshot> = typedExpandoObject(
  { type: ['type', type1Schema], fullPage: ['fullPage', optional(boolean())] },
  'additionalProperties',
  optional(unknown())
);
