/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Direction, directionSchema } from './direction.js';
import { Type5, type5Schema } from './type5.js';

export interface Scroll {
  /** Scroll the page or a specific element */
  type: Type5;
  /** Direction to scroll */
  direction?: Direction;
  /** Query selector for the element to scroll */
  selector?: string;
  additionalProperties?: Record<string, unknown>;
}

export const scrollSchema: Schema<Scroll> = typedExpandoObject(
  {
    type: ['type', type5Schema],
    direction: ['direction', optional(directionSchema)],
    selector: ['selector', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
