/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ScrapeOptions1, scrapeOptions1Schema } from './scrapeOptions1.js';

export interface SearchRequest {
  /** The search query */
  query: string;
  /** Maximum number of results to return */
  limit?: number;
  /** Time-based search parameter */
  tbs?: string;
  /** Location parameter for search results */
  location?: string;
  /** Timeout in milliseconds */
  timeout?: number;
  /** Excludes URLs from the search results that are invalid for other Firecrawl endpoints. This helps reduce errors if you are piping data from search into other Firecrawl API endpoints. */
  ignoreInvalidUrLs?: boolean;
  /** Options for scraping search results */
  scrapeOptions?: ScrapeOptions1;
  additionalProperties?: Record<string, unknown>;
}

export const searchRequestSchema: Schema<SearchRequest> = lazy(() =>
  typedExpandoObject(
    {
      query: ['query', string()],
      limit: ['limit', optional(number())],
      tbs: ['tbs', optional(string())],
      location: ['location', optional(string())],
      timeout: ['timeout', optional(number())],
      ignoreInvalidUrLs: ['ignoreInvalidURLs', optional(boolean())],
      scrapeOptions: ['scrapeOptions', optional(scrapeOptions1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
