/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data6, data6Schema } from './data6.js';

export interface SearchResponse {
  success?: boolean;
  data?: Data6[];
  /** Warning message if any issues occurred */
  warning?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const searchResponseSchema: Schema<SearchResponse> = lazy(() =>
  typedExpandoObject(
    {
      success: ['success', optional(boolean())],
      data: ['data', optional(array(data6Schema))],
      warning: ['warning', optional(nullable(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
