/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MissingContent, missingContentSchema } from './missingContent.js';
import { Rating, ratingSchema } from './rating.js';
import { ValuableSource, valuableSourceSchema } from './valuableSource.js';

/** For 'good', include valuableSources. For 'partial', include valuableSources or missingContent. For 'bad', include missingContent or querySuggestions. */
export interface SearchFeedbackRequest {
  rating: Rating;
  valuableSources?: ValuableSource[];
  missingContent?: MissingContent[];
  querySuggestions?: string;
  origin?: string;
  integration?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const searchFeedbackRequestSchema: Schema<SearchFeedbackRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        rating: ['rating', ratingSchema],
        valuableSources: [
          'valuableSources',
          optional(array(valuableSourceSchema)),
        ],
        missingContent: [
          'missingContent',
          optional(array(missingContentSchema)),
        ],
        querySuggestions: ['querySuggestions', optional(string())],
        origin: ['origin', optional(string())],
        integration: ['integration', optional(nullable(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
