/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Source {
  url?: string;
  title?: string;
  description?: string;
  favicon?: string;
  additionalProperties?: Record<string, unknown>;
}

export const sourceSchema: Schema<Source> = typedExpandoObject(
  {
    url: ['url', optional(string())],
    title: ['title', optional(string())],
    description: ['description', optional(string())],
    favicon: ['favicon', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
