/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data4, data4Schema } from './data4.js';

export interface TeamCreditUsageResponse {
  success?: boolean;
  data?: Data4;
  additionalProperties?: Record<string, unknown>;
}

export const teamCreditUsageResponseSchema: Schema<TeamCreditUsageResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        success: ['success', optional(boolean())],
        data: ['data', optional(data4Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
