/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data5, data5Schema } from './data5.js';

export interface TeamTokenUsageResponse {
  success?: boolean;
  data?: Data5;
  additionalProperties?: Record<string, unknown>;
}

export const teamTokenUsageResponseSchema: Schema<TeamTokenUsageResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        success: ['success', optional(boolean())],
        data: ['data', optional(data5Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
