/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type6
 */
export enum Type6 {
  Scrape = 'scrape',
}

/**
 * Schema for Type6
 */
export const type6Schema: Schema<Type6> = stringEnum(Type6);
