/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type7
 */
export enum Type7 {
  ExecuteJavascript = 'executeJavascript',
}

/**
 * Schema for Type7
 */
export const type7Schema: Schema<Type7> = stringEnum(Type7);
