/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type2
 */
export enum Type2 {
  Click = 'click',
}

/**
 * Schema for Type2
 */
export const type2Schema: Schema<Type2> = stringEnum(Type2);
