/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Visibility
 */
export enum Visibility {
  Visible = 'visible',
  Hidden = 'hidden',
}

/**
 * Schema for Visibility
 */
export const visibilitySchema: Schema<Visibility> = stringEnum(Visibility);
