/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type, typeSchema } from './type.js';

export interface Wait {
  /** Wait for a specified amount of milliseconds */
  type: Type;
  /** Number of milliseconds to wait */
  milliseconds?: number;
  /** Query selector to find the element by */
  selector?: string;
  additionalProperties?: Record<string, unknown>;
}

export const waitSchema: Schema<Wait> = typedExpandoObject(
  {
    type: ['type', typeSchema],
    milliseconds: ['milliseconds', optional(number())],
    selector: ['selector', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
