/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Event, eventSchema } from './event.js';

/** A webhook specification object. */
export interface Webhook1 {
  /** The URL to send the webhook to. This will trigger for crawl started (crawl.started), every page crawled (crawl.page) and when the crawl is completed (crawl.completed or crawl.failed). The response will be the same as the `/scrape` endpoint. */
  url: string;
  /** Headers to send to the webhook URL. */
  headers?: Record<string, string>;
  /** Custom metadata that will be included in all webhook payloads for this crawl */
  metadata?: unknown;
  /** Type of events that should be sent to the webhook URL. (default: all) */
  events?: Event[];
  additionalProperties?: Record<string, unknown>;
}

export const webhook1Schema: Schema<Webhook1> = typedExpandoObject(
  {
    url: ['url', string()],
    headers: ['headers', optional(dict(string()))],
    metadata: ['metadata', optional(unknown())],
    events: ['events', optional(array(eventSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
