/**
 * Firecrawl APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Type3, type3Schema } from './type3.js';

export interface WriteText {
  /** Write text into an input field, text area, or contenteditable element. Note: You must first focus the element using a 'click' action before writing. The text will be typed character by character to simulate keyboard input. */
  type: Type3;
  /** Text to type */
  text: string;
  additionalProperties?: Record<string, unknown>;
}

export const writeTextSchema: Schema<WriteText> = typedExpandoObject(
  { type: ['type', type3Schema], text: ['text', string()] },
  'additionalProperties',
  optional(unknown())
);
